# Generated by Django 6.0.1 on 2026-02-24 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('spot', models.ForeignKey(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='spots.spot')),
            ],
            options={
                'db_table': 'menu_items',
            },
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('spot', models.ForeignKey(db_column='spot_id', on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='spots.spot')),
            ],
            options={
                'db_table': 'opening_hours',
                'unique_together': {('spot', 'day_of_week')},
            },
        ),
    ]
